# Generated by Django 4.1.5 on 2023-02-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSP', models.CharField(max_length=40)),
                ('self_phone_number', models.IntegerField(blank=True)),
                ('home_phone_number', models.IntegerField(blank=True)),
                ('passport_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Линые данные',
                'verbose_name_plural': 'Личные данные',
            },
        ),
    ]
