# Generated by Django 4.1.5 on 2023-02-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_operators', '0001_initial'),
        ('list_prichini', '0001_initial'),
        ('list_actions', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSP', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=40, null=True)),
                ('login', models.CharField(max_length=40, null=True)),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_actions.actions')),
                ('adressat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_operators.operators')),
                ('prichina_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_prichini.prichini')),
            ],
            options={
                'verbose_name': 'Линые данные',
                'verbose_name_plural': 'Личные данные',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
