# Generated by Django 4.1.5 on 2023-02-12 20:29

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_reg_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='login',
            field=models.CharField(default=user.models.User_reg.login_set, max_length=40, null=True),
        ),
    ]
