# Generated by Django 4.1.5 on 2023-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_home_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
