# Generated by Django 4.1.5 on 2023-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_reg_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='login',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
