# Generated by Django 4.1.5 on 2023-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_reg_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='login',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
