# Generated by Django 4.1.5 on 2023-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_reg_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='group_user',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
