# Generated by Django 4.1.5 on 2023-02-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_actions', '0001_initial'),
        ('user', '0014_alter_user_reg_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='action_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='list_actions.actions'),
        ),
    ]
