# Generated by Django 4.1.5 on 2023-02-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0016_alter_user_reg_action_id_alter_user_reg_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='group_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
