# Generated by Django 4.1.5 on 2023-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_reg_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='group_user',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='group',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
