# Generated by Django 4.1.5 on 2023-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_user_reg_group_user_reg_data_vidachi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='data_vidachi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
