# Generated by Django 4.1.5 on 2023-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_reg_group_user_alter_user_reg_nsp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='group_user',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
