# Generated by Django 4.1.5 on 2023-02-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_reg_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='group_user',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='Группа пользователя'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='login',
            field=models.CharField(blank=True, editable=False, help_text='Создается автоматически', max_length=40, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(help_text='Длина пароля до 40 символов', max_length=40, null=True, verbose_name='Пароль'),
        ),
    ]
