# Generated by Django 4.1.5 on 2023-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_reg_group_user_alter_user_reg_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(blank=True, help_text='Длина пароля до 40 символов', max_length=40, null=True, verbose_name='Пароль'),
        ),
    ]
