# Generated by Django 4.1.5 on 2023-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_reg_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='data_vidachi',
            field=models.DateField(null=True, verbose_name='Дата выдачи пароля'),
        ),
    ]
