# Generated by Django 4.1.5 on 2023-02-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_operators', '0001_initial'),
        ('user', '0029_remove_user_reg_adressat_user_reg_adressat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='adressat',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='adressat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_operators.operators', verbose_name='Адрессат'),
        ),
    ]
