# Generated by Django 4.1.5 on 2023-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_operators', '0001_initial'),
        ('user', '0031_remove_user_reg_adressat_user_reg_adressat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='adressat',
            field=models.ManyToManyField(blank=True, null=True, to='list_operators.operators', verbose_name='Адрессат'),
        ),
    ]
